http:
  routers:
    redirect-to-https:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
        - redirect-https
      service: noop@internal
      priority: 1

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
    byo-rate-limit:
      rateLimit:
        average: 50
        burst: 100

tls:
  options:
    default:
      minVersion: "VersionTLS13"